// What is javascript

/*
-> JavaScript is a dynamic computer programming language.
-> It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
-> JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.Complementary to and integrated with HTML.Open and cross-platform
*/

/****   JavaScript Values   ****/
//  -> The JavaScript syntax defines two types of values

/*
    -> Fixed values are called Literals.
    -> Variable values are called Variables.
 */

/**** Using console in javascript ****/

/**** var variable type / box variable name / = assignement / 60 assiged values ****/

// javascript language case-sensitive 

/**************** variable using var() in javascript *************************/
{
    var box = "Livescript";

    var box_1 = "javascript";

    var box_2 = 10;

    var box_3 = 20;

    var box_4 = box_2 + box_3;

    //   console.log(box_4);
    //   ****************** type of run *****************//
    console.log(box);
    document.write(box_1);
    document.getElementById("demo1").innerHTML = box_2;
}
{
    var Names = "1.Names";
    var names = "names";
    console.log(Names);
    console.log(names);

}
{
    var number1 = 15;
    var number2 = 2;
    console.log(number1 ** number2);

    // 15*15=225
}
{
    // var -> same variable name define
    var box1 = "toys";
    var box1 = 45;
    var box1 = 'cloths';
    console.log(box1);

}
{
    //  not used keyword
    box = "apple"
    box1 = "45"
    console.log(box);
}

// /*******New Html Element Add In Though Javascript *********/
{
var newlement = document.createElement("h1");
newlement.textContent="hello world";
document.body.appendChild(newlement);

var newlement = document.createElement("marquee", "option");
newlement.textContent="hello";
document.body.appendChild(newlement);

var newlement = document.createElement("pre");
newlement.textContent="How are you!";
document.body.appendChild(newlement);
}

document.write('hello javascript!');

// // js comments

// // single-line comments
// /* multi-line
//  comments*/

// //  Template literals
{
    var _nameone = "5";
    var name20 = '5';

    console.log(_nameone);
    console.log(typeof (_nameone));   //string  "" ''
}

{
    alert("_nameone + ${name20}")
    alert(`${_nameone}+${name20}`);

}

// // rules for Naming in javascript variables

// {
//     // valid
//     let a= "hello";
//     let _a= "hello";
//     let $a= "hello";
// }

// JavaScript is case-sensitive. So y and Y are different variables

{
    // let y = "hi";
    // let Y = 5;

    // console.log(y);
    // console.log(Y); 
}

// Keywords cannot be used as variable names.

{
    //invalid
    // let new = 5; // Error! new is a keyword.
}

/*  
Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign. After first letter we can use digits (0 to 9), for example value1. JavaScript variables are case sensitive, for example x and X are different variables.
*/